### ISSUE TITLE
buttonize Submit form with bootstrap 4

### ISSUE THREAD

**Issue by bbest** [ecoquants/findinghal#5]
Want the submit link to look like:

![image](https://user-images.githubusercontent.com/2837257/116736861-54108980-a9a5-11eb-80c9-2c7777478c57.png)

Reference for creating buttons in Bootstrap:

* [Buttons · Bootstrap](https://getbootstrap.com/docs/4.0/components/buttons/)

Want  to use the latest Bootstrap 4 for things like cards, which can be implemented with [bslib](https://rstudio.github.io/bslib), otherwise Rmarkdown defaults to Bootstrap 3.

**Comment by bbest** [comment]
Fixed with commit:

- [+ bootstrap 4, submit button with fontawesome icon · ecoquants/findinghal@ae8b3d8](https://github.com/ecoquants/findinghal/commit/ae8b3d8d453ee218528b59ca5966ede223542762)

**Comment by bbest** [comment]
* [Get started • bslib](https://rstudio.github.io/bslib/articles/bslib.html#bootswatch)
* [Bootswatch: Free themes for Bootstrap](https://bootswatch.com/)

To implement, update [_site.yml](https://github.com/ecoquants/findinghal/blob/main/_site.yml) with:

```yaml
output:
  html_document:
  # requires bslib R package to be installed
    theme:
      version: 4
      bootswatch: cerulean
```
